name: 74 Ems
favicon: null
layout_spectrum: 0.5562981604598463
typography_spectrum: 0.21229765750467777
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.43137265648692846
  lightness: 0.40951327816583216
  saturation: 0.9160131923854351
  rhythmicContrast: 0.18886942835524678
purpose: []
